configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/n-a-andreibesleaga%2Fcamara-6fb875ed2f8c8580480879bb4894edc3343b4dff2fc99aa67fa032c14bc2aef5.yml
openapi_spec_hash: 6a5d4d9ce2a174c8f1dda35edae0a11e
config_hash: 16b9f9edf9fbd3610d4fdb3a1f31913c
